### ISSUE TITLE
zero launcher start exe 

### ISSUE THREAD

**Issue by wajaa126** [nzgamer41/ZeroLauncher#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1.5]

**Additional context**
i did it all things to do but it doesnt happend i checked also administrator but it cant start how do i start?

**Comment by nzgamer41** [comment]
fill out the other sections, "It doesnt work" isn't enough information. Did you install Node.js? Have you installed DirectX? Does it do anything running it with start.bat? Can't fix this until you give more info.
